{% set name = "git-url-parse" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b5f4e3aeb1d693afeee67a3bd4ac063f7206c2e8e46e559f0da0da98445f117

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pbr

test:
  imports:
    - giturlparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/git-url-parse/
  summary: git-url-parse - A simple GIT URL parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
